version: '3.8'

services:
  scip-db:
    image: pgvector/pgvector:pg16
    container_name: scip-postgres
    restart: always
    environment:
      POSTGRES_DB: scip_db
      POSTGRES_USER: scip_admin
      POSTGRES_PASSWORD: ScipSecurePassword123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/seed/init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scip_admin -d scip_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  scip-redis:
    image: redis:7-alpine
    container_name: scip-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
